# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f4b3684f4e5a8c12246c8db6fc679171a9465d1020924b1467e4d30a0fb6cb3d06e1f5fcdbb1aa8327f77f7f0630579ba7693f63b795bc9fea26ac99141fe563

test:
  secret_key_base: d9e2a438a93ba6ac57b26af39dfae5d29bcf2637d5fee92f9962fac165550427a46c9eb2607954ca4f76d5970e7fd2a629a0daebc9141452e6a470826c5c96ac

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
